# typed: true
# frozen_string_literal: true

require "action_controller/railtie"
require "action_mailer/railtie"
require "action_text/engine"
require "action_view/railtie"
require "active_job"
require "active_job/railtie"
require "active_job/test_helper"
require "active_model"
require "active_model/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "active_support/all"
require "active_support/core_ext/integer/time"
require "rails"
require "rails/test_help"
require "rails/test_unit/railtie"
require "sorbet-runtime"
