default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("DB_POOL_SIZE") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
<%= ENV['DB_PASSWORD'] && "  password: #{ENV['DB_PASSWORD']}" %>

development:
  <<: *default
  database: tapioca_markn_test
  gssencmode: disable # https://github.com/rails/rails/issues/38560 happens on m1
